// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Swy5J510eZi09yqa0MGeHZ-snh7mPWE',
    appId: '1:37513327793:web:6090339ee9556d13859e90',
    messagingSenderId: '37513327793',
    projectId: 'chatapp-23932',
    authDomain: 'chatapp-23932.firebaseapp.com',
    storageBucket: 'chatapp-23932.appspot.com',
    measurementId: 'G-C3CS09NDNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Qzm-vEgDePM2ekCE95W6Ym41RPBOucE',
    appId: '1:37513327793:android:cf89e0279995a342859e90',
    messagingSenderId: '37513327793',
    projectId: 'chatapp-23932',
    storageBucket: 'chatapp-23932.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDZ_eWs6XtOLEG8OoRR2FqVFvwqDKQO7g',
    appId: '1:37513327793:ios:ec8ed60a46834dc8859e90',
    messagingSenderId: '37513327793',
    projectId: 'chatapp-23932',
    storageBucket: 'chatapp-23932.appspot.com',
    iosClientId: '37513327793-203h6e9a2trsa3jp3gl4eod7io2dv37n.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDZ_eWs6XtOLEG8OoRR2FqVFvwqDKQO7g',
    appId: '1:37513327793:ios:ec8ed60a46834dc8859e90',
    messagingSenderId: '37513327793',
    projectId: 'chatapp-23932',
    storageBucket: 'chatapp-23932.appspot.com',
    iosClientId: '37513327793-203h6e9a2trsa3jp3gl4eod7io2dv37n.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
